### ISSUE TITLE
Suggestion: Add Food Storage, Glassjar Storage for Food/Dust/Liquid

### ISSUE THREAD

**Issue by pewblaze** [chimericdream/minekea-fabric#15]
Suggestion:

Storage for Food would be really nice. Maybe with Compa. for Croptopia :)

Also glass jars. Maybe for food, dusts, water/lava :)

**Comment by chimericdream** [comment]
I have this implemented in the main branch now. I am hoping to have the next big update pushed out later this week or weekend!

For the time being, I don't think I will be adding compatibility for other mods' food items. I certainly _want_ to, but I struggled to find a way to dynamically display a good texture within the jar for anything that isn't a full block. So the textures I have at the moment are actual files and not dynamic. This means I would have to create a new texture for each and every food item I want to support, which just isn't feasible right now. I definitely want to do more research and see what I can do to make it easier to add this kind of support, though! I will create a new GitHub issue to track that aspect of your request.

Thanks for the suggestion!
