### ISSUE TITLE
[1.18.2] Incompatible with BCLib?

### ISSUE THREAD

**Issue by pewblaze** [chimericdream/minekea-fabric#16]
Hi, im not sure if its incompatible or what happens exactly.
I cant start the game when BCLib is also installed. (https://www.curseforge.com/minecraft/mc-mods/bclib)
It crashes.

Here's the latest.log
https://gist.github.com/pewblaze/559beb4c9852b60a14e5f16fb98f436f

**Comment by Piotr-Aueternum** [comment]
Same for me in 1.18.1
https://gist.github.com/Piotr-Aueternum/9a5650d35b4e8ae8b19934752dcd6d51

**Comment by chimericdream** [comment]
I'll look into this and see if I can get a patch out this weekend. Thanks for letting me know!

**Comment by chimericdream** [comment]
I just uploaded version 2.1.1 for 1.17.1, 1.18.1, and 1.18.2 which should fix this issue. I tested all three locally with BCLib by itself, so they _should_ work, but let me know if there are still any issues.

Thanks again!

**Comment by Piotr-Aueternum** [comment]
It works on 1.18.1, thanks :D
