### ISSUE TITLE
[Bug] Crash With Archon 

### ISSUE THREAD

**Issue by HacoKavanah** [chimericdream/minekea-fabric#23]
Most likely will happen with many other mods as well.

I tried to put staff of the undead from that mod to a display case. However, this crashed the game. I'd imagine it is because right clicking with the staff also commences a summoning of mobs.
[crash-2022-04-19_18.29.47-client.txt](https://github.com/chimericdream/minekea-fabric/files/8514407/crash-2022-04-19_18.29.47-client.txt)

**Comment by chimericdream** [comment]
@HacoKavanah I am trying to reproduce the bug but am having some trouble. Looking at the crash report, it appears that the code is trying to set an invalid rotation value for the staff when you insert it. Can you walk me through what you did to trigger it? I've tried inserting the staff from as many different angles and positions as I can manage, but it always goes into the case.

If you are still able to reproduce in your environment, can you try this version? I added an extra check to ensure the rotation value stays within the allowed range. If this works for you, I will get a patched version uploaded to CurseForge today.

[minekea-fabric-1.18.2-2.3.0-hotfix.23.jar](https://drive.google.com/file/d/1-lhvjmSxUJ2WYETGHhl1tD4W0vHOnMyc/view?usp=sharing)

**Comment by HacoKavanah** [comment]
There is nothing more I can tell. It has happened to me two times now, out of pure coincidence. I simply put random items in display cases. I'd say to release the patched version and if the crash still occurs, I'll let you know.

**Comment by chimericdream** [comment]
Version 2.3.1 of the mod has been uploaded to CurseForge for all supported versions. Once it's approved, you should be able to update and hopefully not crash your game.

Thanks again for letting me know!
