### ISSUE TITLE
[Bug] Redwood Display Case

### ISSUE THREAD

**Issue by HacoKavanah** [chimericdream/minekea-fabric#25]
After the reign of evil rotation, we finally have working display cases! Well, sort of. Redwood display case doesn't actually display anything when we put anything in it.

**Comment by HacoKavanah** [comment]
I'll get to play again today but ye only redwood since we didn't get to test the others.

**Comment by chimericdream** [comment]
I just had a realization about why this is happening. I have some family stuff going on this morning and early afternoon, but I should be able to get a fix out this evening. Sorry again, and thanks for your patience!

I hope all of these little (but still annoying) bugs haven't put you and your server mates off the mod. As a fairly new modder (albeit an experienced programmer), it has been super rewarding to see other people using and getting excited about my work!

![92b5b07b0511b84519ce3c63ed880a5f043d6735e4e8e8a0841ecd6e22599ac1.jpg](https://user-images.githubusercontent.com/198075/164984418-5c661bde-c610-43c7-a86a-e0d67a1a8fc5.jpg)

**Comment by chimericdream** [comment]
I just pushed version 2.4.0, which should fix this issue. I had a pretty big oversight in the sense that ensured only the vanilla versions of things like shelves and display cases actually had a block entity associated with them. _sigh_

With any luck, this will be the last major frustration/mistake related to mod compatibility, but I'm sure I will find new ways to break stuff in the future.

Thanks!
