### ISSUE TITLE
error with latest minekea mod

### ISSUE THREAD

**Issue by rsdworker** [chimericdream/minekea-fabric#27]
net.fabricmc.loader.impl.FormattedException: net.fabricmc.loader.impl.discovery.ModResolutionException: Mod resolution encountered an incompatible mod set!
A potential solution has been determined:
	 - Replace mod 'Runtime Resource Pack' (advanced_runtime_resource_pack) 0.3.10 and mod 'Runtime Resource Pack' (advanced_runtime_resource_pack) 0.5.4 (C:\Users\User\Documents\Curse\Minecraft\Instances\(farbic) metro world\mods\arrp-0.5.4.jar) with mod 'Runtime Resource Pack' (advanced_runtime_resource_pack), version 0.5.5.
Unmet dependency listing:
	 - Mod 'Minekea' (minekea) 2.4.1 requires version 0.5.5 of mod 'Runtime Resource Pack' (advanced_runtime_resource_pack), but only the wrong versions are present: 0.5.4/0.3.10!
		 - Mod 'Runtime Resource Pack' (advanced_runtime_resource_pack) 0.5.4 is being loaded from C:\Users\User\Documents\Curse\Minecraft\Instances\(farbic) metro world\mods\arrp-0.5.4.jar
		 - Mod 'Runtime Resource Pack' (advanced_runtime_resource_pack) 0.3.10 is being provided through e.g. C:\Users\User\Documents\Curse\Minecraft\Instances\(farbic) metro world\mods\Modern-Industrialization-0.7.5.jar -> META-INF/jars/arrp-0.3.10.jar
Inactive mods:
	 - mod 'Runtime Resource Pack' (advanced_runtime_resource_pack) 0.5.4, reason: to replace
	 - mod 'wthit' (wthit) 3.11.0, reason: newer version active
	 - mod 'Runtime Resource Pack' (advanced_runtime_resource_pack) 0.3.10, reason: to replace
	 - mod 'Auto Config v1 Updated' (autoconfig1u) 3.3.1, reason: same version active
	 - mod 'Cloth Basic Math' (cloth-basic-math) 0.5.1, reason: newer version active
	 - mod 'Cloth Common Events v1' (cloth-common-events-v1) 1.5.47, reason: newer version active
	 - mod 'Cloth Config v4' (cloth-config2) 5.0.33, reason: newer version active
	 - mod 'Cloth Config v4' (cloth-config2) 5.0.34, reason: newer version active
	 - mod 'Cloth Config v5' (cloth-config2) 5.0.38, reason: newer version active
	 - mod 'Fabric API Base' (fabric-api-base) 0.1.3+12a8474cfa, reason: newer version active
	 - mod 'Fabric API Base' (fabric-api-base) 0.1.3+12a8474c34, reason: newer version active
	 - mod 'Fabric API Base' (fabric-api-base) 0.3.0+c88702897d, reason: newer version active
	 - mod 'Fabric API Base' (fabric-api-base) 0.3.0+a02b44633d, reason: newer version active
	 - mod 'Fabric API Base' (fabric-api-base) 0.3.0+a02b446313, reason: newer version active
	 - mod 'Fabric API Base' (fabric-api-base) 0.4.0+cf39a74318, reason: newer version active
	 - mod 'Fabric Command API (v1)' (fabric-command-api-v1) 1.1.2+6cefd57713, reason: newer version active
	 - mod 'Fabric Events Interaction (v0)' (fabric-events-interaction-v0) 0.4.9+a722d8c013, reason: newer version active
	 - mod 'Fabric Lifecycle Events (v1)' (fabric-lifecycle-events-v1) 1.4.4+a02b446313, reason: newer version active
	 - mod 'Fabric Networking API (v1)' (fabric-networking-api-v1) 1.0.12+6cefd57713, reason: newer version active
	 - mod 'Fabric Networking API (v1)' (fabric-networking-api-v1) 1.0.14+cf39a74318, reason: newer version active
	 - mod 'Fabric Resource Loader (v0)' (fabric-resource-loader-v0) 0.4.7+b7ab61213d, reason: newer version active
	 - mod 'Fabric Resource Loader (v0)' (fabric-resource-loader-v0) 0.4.8+a00e834b18, reason: newer version active
	 - mod 'Fabric Screen API (v1)' (fabric-screen-api-v1) 1.0.4+198a96213d, reason: newer version active
	 - mod 'LibBlockAttributes' (libblockattributes) 0.9.0-pre.2, reason: newer version active
	 - mod 'LibBlockAttributes' (libblockattributes) 0.9.0, reason: same version active
	 - mod 'LibBlockAttributes (Core)' (libblockattributes_core) 0.9.0-pre.2, reason: newer version active
	 - mod 'LibBlockAttributes (Core)' (libblockattributes_core) 0.9.0, reason: same version active
	 - mod 'LibBlockAttributes (Fluids)' (libblockattributes_fluids) 0.9.0-pre.2, reason: newer version active
	 - mod 'LibBlockAttributes (Fluids)' (libblockattributes_fluids) 0.9.0, reason: same version active
	 - mod 'LibBlockAttributes (Items)' (libblockattributes_items) 0.9.0-pre.2, reason: newer version active
	 - mod 'LibBlockAttributes (Items)' (libblockattributes_items) 0.9.0, reason: same version active
	 - mod 'LibGui' (libgui) 4.1.1+1.17.1-rc1, reason: newer version active
	 - mod 'LibGui' (libgui) 4.1.6+1.17.1, reason: newer version active
	 - mod 'LibMultiPart' (libmultipart) 0.6.0, reason: same version active
	 - mod 'Lib Network Stack' (libnetworkstack) 0.5.0, reason: same version active
	 - mod 'Magna' (magna) 0.4.0-1.17.1, reason: newer version active
	 - mod 'Patchouli' (patchouli) 1.17.1-56-FABRIC, reason: newer version active
	 - mod 'Reborn Core' (reborncore) 5.0.11-beta, reason: same version active
	 - mod 'Energy' (team_reborn_energy) 0.1.1, reason: newer version active
	at net.fabricmc.loader.impl.FabricLoaderImpl.load(FabricLoaderImpl.java:189)
	at net.fabricmc.loader.impl.launch.knot.Knot.init(Knot.java:142)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:71)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
Caused by: net.fabricmc.loader.impl.discovery.ModResolutionException: Mod resolution encountered an incompatible mod set!
A potential solution has been determined:
	 - Replace mod 'Runtime Resource Pack' (advanced_runtime_resource_pack) 0.3.10 and mod 'Runtime Resource Pack' (advanced_runtime_resource_pack) 0.5.4 (C:\Users\User\Documents\Curse\Minecraft\Instances\(farbic) metro world\mods\arrp-0.5.4.jar) with mod 'Runtime Resource Pack' (advanced_runtime_resource_pack), version 0.5.5.
Unmet dependency listing:
	 - Mod 'Minekea' (minekea) 2.4.1 requires version 0.5.5 of mod 'Runtime Resource Pack' (advanced_runtime_resource_pack), but only the wrong versions are present: 0.5.4/0.3.10!
		 - Mod 'Runtime Resource Pack' (advanced_runtime_resource_pack) 0.5.4 is being loaded from C:\Users\User\Documents\Curse\Minecraft\Instances\(farbic) metro world\mods\arrp-0.5.4.jar
		 - Mod 'Runtime Resource Pack' (advanced_runtime_resource_pack) 0.3.10 is being provided through e.g. C:\Users\User\Documents\Curse\Minecraft\Instances\(farbic) metro world\mods\Modern-Industrialization-0.7.5.jar -> META-INF/jars/arrp-0.3.10.jar
Inactive mods:
	 - mod 'Runtime Resource Pack' (advanced_runtime_resource_pack) 0.5.4, reason: to replace
	 - mod 'wthit' (wthit) 3.11.0, reason: newer version active
	 - mod 'Runtime Resource Pack' (advanced_runtime_resource_pack) 0.3.10, reason: to replace
	 - mod 'Auto Config v1 Updated' (autoconfig1u) 3.3.1, reason: same version active
	 - mod 'Cloth Basic Math' (cloth-basic-math) 0.5.1, reason: newer version active
	 - mod 'Cloth Common Events v1' (cloth-common-events-v1) 1.5.47, reason: newer version active
	 - mod 'Cloth Config v4' (cloth-config2) 5.0.33, reason: newer version active
	 - mod 'Cloth Config v4' (cloth-config2) 5.0.34, reason: newer version active
	 - mod 'Cloth Config v5' (cloth-config2) 5.0.38, reason: newer version active
	 - mod 'Fabric API Base' (fabric-api-base) 0.1.3+12a8474cfa, reason: newer version active
	 - mod 'Fabric API Base' (fabric-api-base) 0.1.3+12a8474c34, reason: newer version active
	 - mod 'Fabric API Base' (fabric-api-base) 0.3.0+c88702897d, reason: newer version active
	 - mod 'Fabric API Base' (fabric-api-base) 0.3.0+a02b44633d, reason: newer version active
	 - mod 'Fabric API Base' (fabric-api-base) 0.3.0+a02b446313, reason: newer version active
	 - mod 'Fabric API Base' (fabric-api-base) 0.4.0+cf39a74318, reason: newer version active
	 - mod 'Fabric Command API (v1)' (fabric-command-api-v1) 1.1.2+6cefd57713, reason: newer version active
	 - mod 'Fabric Events Interaction (v0)' (fabric-events-interaction-v0) 0.4.9+a722d8c013, reason: newer version active
	 - mod 'Fabric Lifecycle Events (v1)' (fabric-lifecycle-events-v1) 1.4.4+a02b446313, reason: newer version active
	 - mod 'Fabric Networking API (v1)' (fabric-networking-api-v1) 1.0.12+6cefd57713, reason: newer version active
	 - mod 'Fabric Networking API (v1)' (fabric-networking-api-v1) 1.0.14+cf39a74318, reason: newer version active
	 - mod 'Fabric Resource Loader (v0)' (fabric-resource-loader-v0) 0.4.7+b7ab61213d, reason: newer version active
	 - mod 'Fabric Resource Loader (v0)' (fabric-resource-loader-v0) 0.4.8+a00e834b18, reason: newer version active
	 - mod 'Fabric Screen API (v1)' (fabric-screen-api-v1) 1.0.4+198a96213d, reason: newer version active
	 - mod 'LibBlockAttributes' (libblockattributes) 0.9.0-pre.2, reason: newer version active
	 - mod 'LibBlockAttributes' (libblockattributes) 0.9.0, reason: same version active
	 - mod 'LibBlockAttributes (Core)' (libblockattributes_core) 0.9.0-pre.2, reason: newer version active
	 - mod 'LibBlockAttributes (Core)' (libblockattributes_core) 0.9.0, reason: same version active
	 - mod 'LibBlockAttributes (Fluids)' (libblockattributes_fluids) 0.9.0-pre.2, reason: newer version active
	 - mod 'LibBlockAttributes (Fluids)' (libblockattributes_fluids) 0.9.0, reason: same version active
	 - mod 'LibBlockAttributes (Items)' (libblockattributes_items) 0.9.0-pre.2, reason: newer version active
	 - mod 'LibBlockAttributes (Items)' (libblockattributes_items) 0.9.0, reason: same version active
	 - mod 'LibGui' (libgui) 4.1.1+1.17.1-rc1, reason: newer version active
	 - mod 'LibGui' (libgui) 4.1.6+1.17.1, reason: newer version active
	 - mod 'LibMultiPart' (libmultipart) 0.6.0, reason: same version active
	 - mod 'Lib Network Stack' (libnetworkstack) 0.5.0, reason: same version active
	 - mod 'Magna' (magna) 0.4.0-1.17.1, reason: newer version active
	 - mod 'Patchouli' (patchouli) 1.17.1-56-FABRIC, reason: newer version active
	 - mod 'Reborn Core' (reborncore) 5.0.11-beta, reason: same version active
	 - mod 'Energy' (team_reborn_energy) 0.1.1, reason: newer version active
	at net.fabricmc.loader.impl.discovery.ModResolver.findCompatibleSet(ModResolver.java:159)
	at net.fabricmc.loader.impl.discovery.ModResolver.resolve(ModResolver.java:45)
	at net.fabricmc.loader.impl.FabricLoaderImpl.setup(FabricLoaderImpl.java:224)
	at net.fabricmc.loader.impl.FabricLoaderImpl.load(FabricLoaderImpl.java:187)
	... 3 more

the mods are already updated but this complains of issue - but I don't understand what is problem

**Comment by chimericdream** [comment]
Which version of Minecraft are you on? It looks like you have ARRP 0.5.4, but 0.5.5 is required.

(Note: I may be able to move the supported version down, but would need to verify)

**Comment by chimericdream** [comment]
I apologize for not getting back to you sooner. I just uploaded 1.17.2-2.4.2 to CurseForge (it may take a few minutes to get approved). I lowered the required version of the ARRP mod to 0.5+, which should hopefully fix the issue for you.

I'll close the ticket for now, but feel free to re-open it if you are still having the same issue.

Thanks for letting me know!
