### ISSUE TITLE
[Visual Bug] Floating Shelf shows a glitch item

### ISSUE THREAD

**Issue by HacoKavanah** [chimericdream/minekea-fabric#28]
When my friend took items off the floating shelf, to me it looked like they were still there. But when I clicked to take these glitch items out, they just disappeared but didn't fortunately give me any duplicate items..

**Comment by chimericdream** [comment]
I had a similar issue locally when developing the shelf functionality. It has to do with the block state not syncing to the clients correctly. I'll look into how to fix this in multi-player.

Thanks!

**Comment by chimericdream** [comment]
This is fixed in 2.5.1, which was just published to CurseForge.

Thanks!
