### ISSUE TITLE
Server text output is changed

### ISSUE THREAD

**Issue by Zhyn-exe** [chimericdream/minekea-fabric#38]
"Preparing spawn area:" changes to "menu.preparingSpawn" and does not give a percentage anymore, something to do with changing language?
This is the only thing I noticed changed in the server text output.

Minecraft 1.18.2
Fabric loader 0.14.4
Fabric api 0.51.1
Mod ver 2.5.1

**Comment by chimericdream** [comment]
Oops! I'll try to get a fix out tonight.

**Comment by chimericdream** [comment]
I just uploaded version 2.6.1 which should fix this. Thanks for pointing it out!
