### ISSUE TITLE
Any plan to support MythicMetal+Blockus?

### ISSUE THREAD

**Issue by ardissaps** [chimericdream/minekea-fabric#43]
Thx

**Comment by chimericdream** [comment]
I can definitely look into supporting these. Thanks for the suggestion!

**Comment by ardissaps** [comment]
> I can definitely look into supporting these. Thanks for the suggestion!

Thank you very much!

**Comment by chimericdream** [comment]
I am going to split this into two tickets. I have Mythic Metals support added in, but even partial support for Blockus will consist of over 200 (!) blocks to add variants for. I'd like to get an update pushed out in the next few days, and that many blocks will take some time.

**Comment by chimericdream** [comment]
Added in dev. This will be released with the next version (hopefully this weekend, but we'll see)

**Comment by ardissaps** [comment]
Nice, thanks!
