### ISSUE TITLE
cant start server

### ISSUE THREAD

**Issue by MisterrBrown** [chimericdream/minekea-fabric#51]
hello... i get this error when i run this mod on my server on MC 1.19... but works fine in single player... do you have a clue what could be the problem ?

21.06 19:15:30 [Server] main/ERROR Failed to start the minecraft server
21.06 19:15:30 [Server] INFO java.lang.RuntimeException: Could not execute entrypoint stage 'main' due to errors, provided by 'minekea'!
21.06 19:15:30 [Server] INFO at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.lambda$invoke0$0(EntrypointUtils.java:51) ~[fabric-loader-0.14.8.jar:?]
21.06 19:15:30 [Server] INFO at net.fabricmc.loader.impl.util.ExceptionUtil.gatherExceptions(ExceptionUtil.java:33) ~[fabric-loader-0.14.8.jar:?]
21.06 19:15:30 [Server] INFO at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke0(EntrypointUtils.java:49) ~[fabric-loader-0.14.8.jar:?]
21.06 19:15:30 [Server] INFO at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke(EntrypointUtils.java:35) ~[fabric-loader-0.14.8.jar:?]
21.06 19:15:30 [Server] INFO at net.fabricmc.loader.impl.game.minecraft.Hooks.startServer(Hooks.java:62) ~[fabric-loader-0.14.8.jar:?]
21.06 19:15:30 [Server] INFO at net.minecraft.server.Main.main(Main.java:101) [server-intermediary.jar:?]
21.06 19:15:30 [Server] INFO at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:461) [fabric-loader-0.14.8.jar:?]
21.06 19:15:30 [Server] INFO at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74) [fabric-loader-0.14.8.jar:?]
21.06 19:15:30 [Server] INFO at net.fabricmc.loader.impl.launch.knot.KnotServer.main(KnotServer.java:23) [fabric-loader-0.14.8.jar:?]
21.06 19:15:30 [Server] INFO at net.fabricmc.loader.impl.launch.server.FabricServerLauncher.main(FabricServerLauncher.java:69) [fabric-loader-0.14.8.jar:?]
21.06 19:15:30 [Server] INFO Caused by: java.lang.ExceptionInInitializerError
21.06 19:15:30 [Server] INFO at java.lang.Class.forName0(Native Method) ~[?:?]
21.06 19:15:30 [Server] INFO at java.lang.Class.forName(Class.java:467) ~[?:?]
21.06 19:15:30 [Server] INFO at net.fabricmc.loader.impl.util.DefaultLanguageAdapter.create(DefaultLanguageAdapter.java:50) ~[fabric-loader-0.14.8.jar:?]
21.06 19:15:30 [Server] INFO at net.fabricmc.loader.impl.entrypoint.EntrypointStorage$NewEntry.getOrCreate(EntrypointStorage.java:117) ~[fabric-loader-0.14.8.jar:?]
21.06 19:15:30 [Server] INFO at net.fabricmc.loader.impl.entrypoint.EntrypointContainerImpl.getEntrypoint(EntrypointContainerImpl.java:53) ~[fabric-loader-0.14.8.jar:?]
21.06 19:15:30 [Server] INFO at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke0(EntrypointUtils.java:47) ~[fabric-loader-0.14.8.jar:?]
21.06 19:15:30 [Server] INFO ... 7 more
21.06 19:15:30 [Server] INFO Caused by: java.lang.RuntimeException: Cannot load class net.fabricmc.fabric.api.client.render.fluid.v1.FluidRenderHandler in environment type SERVER
21.06 19:15:30 [Server] INFO at net.fabricmc.loader.impl.transformer.FabricTransformer.transform(FabricTransformer.java:59) ~[fabric-loader-0.14.8.jar:?]
21.06 19:15:30 [Server] INFO at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getPreMixinClassByteArray(KnotClassDelegate.java:454) ~[fabric-loader-0.14.8.jar:?]
21.06 19:15:30 [Server] INFO at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:407) ~[fabric-loader-0.14.8.jar:?]
21.06 19:15:30 [Server] INFO at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.tryLoadClass(KnotClassDelegate.java:323) ~[fabric-loader-0.14.8.jar:?]
21.06 19:15:30 [Server] INFO at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:218) ~[fabric-loader-0.14.8.jar:?]
21.06 19:15:30 [Server] INFO at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:145) ~[fabric-loader-0.14.8.jar:?]
21.06 19:15:30 [Server] INFO at java.lang.ClassLoader.loadClass(ClassLoader.java:520) ~[?:?]
21.06 19:15:30 [Server] INFO at com.chimericdream.minekea.MinekeaMod.<clinit>(MinekeaMod.java:60) ~[minekea-fabric-1.19-3.1.0.jar:?]
21.06 19:15:30 [Server] INFO at java.lang.Class.forName0(Native Method) ~[?:?]
21.06 19:15:30 [Server] INFO at java.lang.Class.forName(Class.java:467) ~[?:?]
21.06 19:15:30 [Server] INFO at net.fabricmc.loader.impl.util.DefaultLanguageAdapter.create(DefaultLanguageAdapter.java:50) ~[fabric-loader-0.14.8.jar:?]
21.06 19:15:30 [Server] INFO at net.fabricmc.loader.impl.entrypoint.EntrypointStorage$NewEntry.getOrCreate(EntrypointStorage.java:117) ~[fabric-loader-0.14.8.jar:?]
21.06 19:15:30 [Server] INFO at net.fabricmc.loader.impl.entrypoint.EntrypointContainerImpl.getEntrypoint(EntrypointContainerImpl.java:53) ~[fabric-loader-0.14.8.jar:?]
21.06 19:15:30 [Server] INFO at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke0(EntrypointUtils.java:47) ~[fabric-loader-0.14.8.jar:?]
21.06 19:15:30 [Server] INFO ... 7 more

**Comment by chimericdream** [comment]
I just uploaded version 3.1.1 to CurseForge, which should fix this issue. It may take a little bit for it to get approved, but generally shouldn't be too long.

I have no idea why it worked fine in 1.18.2 and broke in 1.19, but 🤷 . Let me know if you have any other issues.

**Comment by MisterrBrown** [comment]
Thank you very much for the quick update !! work just fine !!!
