### ISSUE TITLE
Consider Doing BetterNether & BetterEnd Support?

### ISSUE THREAD

**Issue by Akane-N** [chimericdream/minekea-fabric#54]
These Mods have some nice wood types, and there very popular mods too, it would be cool to have furniture to match them as well, would you consider adding support for these in the future maybe? ^~^

**Comment by chimericdream** [comment]
I think that's definitely worth looking into. Thanks for the suggestion!

**Comment by chimericdream** [comment]
Added in dev. This will be released with the next version (hopefully this weekend, but we'll see)
