### ISSUE TITLE
Missing BYG wood type?

### ISSUE THREAD

**Issue by FrogFiesta** [chimericdream/minekea-fabric#55]
I'm not sure if it's just me, but it looks like one of the wood types from Oh the Biomes You'll Go is missing crafting recipes. The white mangrove wood looks like it's in the screenshots for the mods, but doesn't show up in game. Is it possibly due to the wood having it's name changed in the 1.19 version of BYG?

**Comment by chimericdream** [comment]
That's likely what happened, yeah. I remember removing the mangrove type, but I didn't realize they just renamed it. I'll work on getting it re-added in the next update!

**Comment by chimericdream** [comment]
Fixed in dev. This will be released with the next version (hopefully this weekend, but we'll see)
