### ISSUE TITLE
Colored Prismarine Request

### ISSUE THREAD

**Issue by faevyn** [chimericdream/minekea-fabric#56]
I'd love to see prismarine, prismarine bricks, and dark prismarine (in their block, stair, slab, and wall variants as well) in the same colors that are allowed through dyeing.

**Comment by chimericdream** [comment]
I think that sounds interesting. I'll look into it. Thanks for the suggestion!

**Comment by chimericdream** [comment]
Added in dev (along with colored versions of several other blocks). This will be released with the next version (hopefully this weekend, but we'll see)
