### ISSUE TITLE
Suggestion: Add more bookshelves for other mods as compa

### ISSUE THREAD

**Issue by TheButterbrotMan** [chimericdream/minekea-fabric#6]
Ill would suggest adding more compatiblitys for other mods adding bookshelves.

For example BYG.

**Comment by chimericdream** [comment]
This is definitely something I would like to do. I am pretty new to modding, so I'm still getting a feel for all of the APIs and functionality that are available. My current/next goal is to generate the existing textures, blockstates, models, etc dynamically so I don't have to explicitly include textures for every variant. Once I have that figured out, I suspect it will be a lot simpler for me to do something like "generate shelves/storage shelves for everything matching the tag `shelfstorage:some_tag_here`".

Thanks for the suggestion!

**Comment by TheButterbrotMan** [comment]
Check Out my mod Awesome Plates, we used their if a mod is present do this method.

**Comment by chimericdream** [comment]
Yeah, I've seen the `isModLoaded` method. But what I mean is that I'd like to avoid having json and png files for every possible shelf variant for every compatible mod. If possible, I want to dynamically generate both the json files for blockstates/models as well as the actual textures themselves.

**Comment by TheButterbrotMan** [comment]
https://www.curseforge.com/minecraft/mc-mods/dynamic-asset-generator#:~:text=A%20library%20mod%20for%20dynamically,data%20caching%20in%20the%20config.

**Comment by chimericdream** [comment]
I have started working on adding compatibility for BYG, and all I have to say is holy crap they have a lot of wood types!

I should have the next big update out later this week.

**Comment by chimericdream** [comment]
Teaser:
![2022-04-14_01 03 58](https://user-images.githubusercontent.com/198075/163410443-339ec360-669d-421e-bc0d-2360c6223f9e.png)

**Comment by chimericdream** [comment]
BYG support added in 2.2.0! Feel free to request other mods you may be interested in!

[1.17.1](https://www.curseforge.com/minecraft/mc-mods/minekea-fabric/files/3752040)
[1.18.1](https://www.curseforge.com/minecraft/mc-mods/minekea-fabric/files/3752042)
[1.18.2](https://www.curseforge.com/minecraft/mc-mods/minekea-fabric/files/3752043)
