### ISSUE TITLE
Chairs only face one way  no matter what angle you place them from

### ISSUE THREAD

**Issue by Akane-N** [chimericdream/minekea-fabric#60]
**Describe the bug**
for some reason chairs will only face one direction no matter what angle I place them from, which is very inconvenient for decorating with them unfortunately. 

**Expected behavior**
to be able to decide what direction you want them to face like vanilla stairs.

**Environment**
 * Minecraft version: 1.19
 * Minekea version: 1.19-3.2.0.jar

**Comment by chimericdream** [comment]
Well, that's no good. I will take a look and see if I can figure out what's going on. In the meantime, are you able to rotate them with the wrench? That should be a temporary solution until I can fix whatever is happening.
