### ISSUE TITLE
Vertical Stairs and Bookshelf Stairs recipes conflict

### ISSUE THREAD

**Issue by storiofmylife** [chimericdream/minekea-fabric#61]
**Describe the bug**
Both the vertical stairs and bookshelf stairs use the same recipe which defaults to bookshelf variant.

**To Reproduce**
1. Go to craft vertical stairs of any plank
2. Output is the vertical bookshelf stairs

**Expected behavior**
Vertical Stairs should come from spruce planks, while vertical bookshelf stairs should come from bookshelves of that variant. 

**Screenshots**
![2022-07-27_17 07 32](https://user-images.githubusercontent.com/79773725/181373291-08f196b5-5740-4eef-8ed2-9a2ec6ad1274.png)
![2022-07-27_17 07 21](https://user-images.githubusercontent.com/79773725/181373307-5a063213-3859-4750-98e1-ddd9ef916b39.png)

**Environment**
 * Minecraft version: 1.19
 * Minekea version: minekea-fabric-1.19-3.3.1
 * OS: Windows 10 Pro (but also on other systems since this is happening on a public server)

**Comment by chimericdream** [comment]
Thanks for reporting this! I had a feeling I knew what happened, so it was fortunately an easy fix. I just uploaded version 3.3.2 to CurseForge, so it should be available shortly (_usually_ only a few minutes).
