### ISSUE TITLE
BetterNether and BetterEnd bookshelf stairs conflict with regular stairs

### ISSUE THREAD

**Issue by storiofmylife** [chimericdream/minekea-fabric#62]
**Describe the bug**
Hey there back again! The BN and BE bookshelf stairs use the same recipes as the BN and BE stairs. 

**To Reproduce**
1. Go to craft stairs with planks
2. Output overrides to Minekea's bookshelf stairs

**Expected behavior**
Bookshelves would be used for bookshelf stairs rather than planks. 

**Screenshots**
![2022-07-30_10 46 29](https://user-images.githubusercontent.com/79773725/181919793-b083ecef-41b1-4c0b-b02e-34f0db88e754.png)
![2022-07-30_10 47 03](https://user-images.githubusercontent.com/79773725/181919798-f26dd94c-b33c-428b-833f-40ed779bfa61.png)

**Environment**
- Minecraft version: 1.19
- Minekea version: minekea-fabric-1.19-3.3.2
- OS: Windows 10 Pro (but also on other systems since this is happening on a public server)

**Comment by storiofmylife** [comment]
I also noticed that the wool pressure plates override the carpet recipes. Maybe have it so that the pressure plates use 2 carpets instead of 2 wool blocks?

**Comment by chimericdream** [comment]
Thanks for the report! I had the same issue with the vertical bookshelf stairs and didn't think to check the regular variety. I also like your suggestion for the wool pressure plates. I will try to get an update out in the next day or two that addresses these and hopefully one or two other minor issues.

**Comment by storiofmylife** [comment]
Thanks for all your hard work!
