### ISSUE TITLE
Block painter crashes servers

### ISSUE THREAD

**Issue by twixstix** [chimericdream/minekea-fabric#72]
**Describe the bug**
Using the block painter on a server causes the server to crash. The client encounters no crash and is simply kicked back to the multiplayer screen. Using it in single player provides no issue.

**To Reproduce**
1. Right-click on a block with block painter while on a server
2. Get booted from the server, as it has now crashed.

**Environment**
 * Minecraft version: 1.19
 * Minekea version: 3.3.3
 * OS: Linux

**Additional context**
[crash_log.txt](https://github.com/chimericdream/minekea-fabric/files/9492286/crash_log.txt)

**Comment by chimericdream** [comment]
Thanks for the bug report! I'll do some digging and see if I can figure out what's going on.

**Comment by chimericdream** [comment]
Sorry for the long delay on this. I am back to working on Minekea finally, and I think I found the issue here. It should be fixed in the next version.
