### ISSUE TITLE
BYG addon crates break with pickaxe

### ISSUE THREAD

**Issue by yamitami** [chimericdream/minekea-fabric#73]
**Describe the bug**
The preferred tool for the BYG addon crates is set to pickaxe instead of axe.

**To Reproduce**
Every BYG crate I've tried so far will break fast with a pickaxe but at standard speed with an axe. The vanilla wood varieties break with an axe as expected, it looks like it's only the BYG addon crates.

**Expected behavior**
Preferred tool for crates should be the axe.

**Environment**
 * Minecraft version: 1.19.2
 * Minekea version: 1.19.3.3.3
 * OS: Windows 10

**Comment by yamitami** [comment]
The barrels, tables, and chairs also break with a pickaxe instead of the axe, still looks like it's just the BYG addon items that do it.

**Comment by chimericdream** [comment]
Thanks for the report! This will be fixed in the next update. I also proactively checked (and fixed) the required tool for Better End / Better Nether, since it turns out they had the same bug.
