### ISSUE TITLE
BetterEnd / BetterNether Display Cases are Opaque 1.19.2

### ISSUE THREAD

**Issue by AutoRunFail** [chimericdream/minekea-fabric#80]
**Describe the bug**
When using Minekea with BetterEnd and BetterNether, the display cases have opaque glass when placed, though the item block in hand correctly renders clear glass. 

**To Reproduce**
1. Using Fabric Loader 0.14.12, run Minekea 4.02, ARRP 0.6.4, Fabric API 0.72.0+1.19.2, Cloth Config 8.2.88, Better Nether 7.1.2, Better End 2.1.2 and BClib 2.1.5
2. Place a display case from Minekea that uses Better End or Better Nether material (ex: End Lotus Display Case or Nether Sakura Display Case)
3. See Error

**Expected behavior**
The glass should be see through as usual. 

**Screenshots**
![MinekeaDisplayGlitch](https://user-images.githubusercontent.com/105956312/218938151-6bdc8ef4-9c48-43ce-8d95-4efb2c4cec4d.png)

![ModList](https://user-images.githubusercontent.com/105956312/218938333-ec793499-540c-4ce6-a4a1-d7a99b8a850d.png)

**Environment**
 * Minecraft version: 1.19.2
 * Minekea version: 4.0.2
 * OS: WIndows 10

**Additional context**
Vanilla and BYG cases work as expected, just the Better End/Nether mods, and as you can see in the screenshot, it's only the block that seems to have the issue, as the item version is clear. The display case seems to work as expected otherwise - when I place something in it, it is presumably placed, but impossible to see under the opaque glass, and I receive the item back after breaking it. A texture issue I would assume?

**Comment by SplendidAlakey** [comment]
Found the culprit, BetterEnd and BetterNether don't use conventional `stripped_TYPE_log` strings for their stripped versions of logs, but Minekea assumes it does and creates incorrect recipes, resulting in the following errors:

```
[08:22:36] [WARN ] Failed to parse recipe 'minekea:betternether/furniture/display_cases/stripped/rubeus[minecraft:crafting_shaped]'! Falling back to vanilla: com.google.gson.JsonSyntaxException: Unknown item 'betternether:stripped_rubeus_log'
[08:22:36] [WARN ] Failed to parse recipe minekea:betternether/furniture/display_cases/stripped/rubeus[minecraft:crafting_shaped]: com.google.gson.JsonSyntaxException: Unknown item 'betternether:stripped_rubeus_log'
```

`betternether:stripped_rubeus_log` is actually `betternether:rubeus_stripped_log` and that goes for every stripped wood in BE and BN.
