### ISSUE TITLE
Shutter Placement State Orientation Type Crash

### ISSUE THREAD

**Issue by theaceofthespade** [chimericdream/minekea-fabric#87]
**Describe the bug**
When placing shutters, if one accidentally tries to place them on the ground, the game crashes with:
Error: java.lang.IllegalArgumentException: Cannot set property class_2753{name=wall_side, clazz=class net.minecraft.class_2350, values=[north, east, south, west]} to down on Block{minekea:furniture/shutters/acacia}, it is not an allowed value

**To Reproduce**
1. Open game in creative mode - existing or new world
2. Use the creative inventory to acquire shutters (presumably it does not matter how you get the shutters)
3. Try placing (right click) shutters on a ground block 
4. Game freezes and crashes to error above

**Expected behavior**
The shutters should either not place, or place in a "floating" position

**Screenshots**

**Environment**
 * Minecraft version: 1.21, Fabric Launcher 0.16.5
 * Minekea version: 5.0.0
 * OS: Windows 11 Pro

**Additional context**
Only tested clientside.
I'm running roughly 250 mods, so there's plenty of room for conflict, but I'm fairly certain this is just a regular bug.
I have some limited mod experience, and it looks like it just needs to do an additional check on the placement state orientation before trying to modify the blockstate.

**Comment by chimericdream** [comment]
Thanks for reporting this, as well as submitting a PR! I am planning to try and upload a new release tonight, so I'll make sure this fix makes it in.

**Comment by theaceofthespade** [comment]
Thank you so much for the lovely mod!  I'm glad I was able to provide a little bit of support!
